apiVersion: 1
datasources:
  - name: Social metrics
    uid: social-prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
  - name: Social traces
    uid: social-tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
  - name: Social logs
    uid: social-loki
    type: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([0-9a-f]{32})"'
          datasourceUid: social-tempo
          url: '$${__value.raw}'
